---
- name: Master Installation
  hosts: master  #group "master" is declared in the 'hosts' file
  remote_user: root #ansible connexion used the "root" user
  

  tasks:
    - name: Package Installation
      apt: name={{ item }} update_cache=yes  state=latest #apt update & last version installed
      with_items: #apt install x
        - isc-dhcp-server 
        - ssh
        - lxd
        - python3-lxc
        - lxc-utils
        - lxctl
        - htop
        - bridge-utils
        - libvirt-bin
        - debootstrap
        - ifupdown
        - net-tools
        - ntpdate
        - nmap
        - git
        - ansible
        - nfs-kernel-server

###### DHCP CONFIGURATION ######

    - name: DHCP configuration
      become: yes
      copy:
        src: /etc/ansible/templates/dhcp.conf.june.template
        dest: /etc/dhcp
        owner: nobody
        group: nogroup
        mode: '0644'

    - name: Setting up the DHCP default file
      become: yes
      copy:
        src: /etc/ansible/templates/isc-dhcp-server.template
        dest: /etc/default/isc-dhcp-server
        owner: nobody
        group: nogroup
        mode: '0644'

###### IPTABLES CONFIGURATION ######

    - name: Configuring iptables script
      become: yes
      copy:
        src: /etc/ansible/templates/script_iptables.sh.template
        dest: /home/master/script_iptables.sh
        owner: nobody
        group: nogroup
        mode: '0644'

    - name: Configuring iptables service
      become: yes
      copy:
        src: /etc/ansible/templates/script_iptables.service.template
        dest: /etc/systemd/system/script_iptables.service
        owner: nobody
        group: nogroup
        mode: '0644'

    - name: Converting a typicall upstart job to a systemd one
      command: "{{item}}"
      with_items:
        - systemctl daemon-reload
        - systemctl enable script_iptables

###### LXC CONFIGURATION ######

    - name: Setting the Network configurations
      become: yes
      copy:
        src: /etc/ansible/templates/netplan-master.template
        dest: /etc/netplan/50-cloud-init.yaml
        owner: nobody
        group: nogroup
        mode: '0644'

    - name: Setting up LXC/LXD Networking
      command: "{{item}}"
      with_items:
        - lxd init --auto
        - lxc config set core.https_address [::]:8443
        - lxc profile device set default eth0 parent netbr0
        - service lxd restart

###### NFS CONFIGURATION ######

    - name: Getting the export file
      become: yes
      copy:
        src: /etc/ansible/templates/exports.june.template
        dest: /etc/exports
        owner: nobody
        group: nogroup
        mode: '0644'

    - name: Configuring NFS server
      command: "{{item}}"
      with_items:
        - mkdir -p /mnt/sharedfolder
        - sudo chown nobody:nogroup /mnt/sharedfolder
        - sudo chmod 777 /mnt/sharedfolder
      
    - name: Sharing the folder
      command: exportfs -rav #VERY important step

##### ANSIBLE CONFIGURATION #####

    - name: Importing the ansible directory
      become: yes
      copy:
        src: /etc/ansible/templates/ansible.template
        dest: /etc/ansible
        owner: nobody
        group: nogroup
        mode: '0644'

###### RESTARTING SERVICES AT THE END ######

    - name: Restarting services
      command: systemctl restart isc-dhcp-server networking ssh sshd nfs-kernel-server

...
