---
- name: Package Installation
  hosts: pxe # declared in the 'hosts' file
  remote_user: root #ansible connexion used the "root" user

  tasks:
    - name: Packages install
      apt: name={{ item }} update_cache=yes  state=latest #updating versions or installing the last one
      with_items: #apt install (package)
        - ssh
        - htop
        - libvirt-bin
        - debootstrap
        - ifupdown
        - ntpdate
        - net-tools
        - inetutils-inetd
        - tftpd-hpa

##### PXE CONFIGURATION #####

## tftpd-hpa file ##
    - name: Changing the tftpd-hpa default config
      command: scp root@192.168.150.199:/etc/ansible/templates/tftpd-hpa.template /etc/default/

    - name: Moving the old file
      command: mv /etc/default/tftpd-hpa /etc/default/tftpd-hpa.bkp

    - name: Placing the new one
      command: mv /etc/default/tftpd-hpa.template /etc/default/tftpd-hpa

## inetd.conf file ##
    - name: Changing inetd.conf config
      command: scp root@192.168.150.199:/etc/ansible/templates/inetd.conf.template /etc/

    - name: Moving the old file
      command: mv /etc/inetd.conf /etc/inetd.conf.bkp

    - name: Placing the new one
      command: mv /etc/inetd.conf.template /etc/inetd.conf

    - name: Restarting the service
      command: systemctl restart tftpd-hpa

## tftpboot files ##
    - name: Changing the tftpboot files
      command: scp -r root@192.168.150.199:/etc/ansible/templates/tftpboot.template /var/lib/

    - name: Moving the old file
      command: mv /var/lib/tftpboot /var/lib/tftpboot.bkp

    - name: Placing the new one
      command: mv /var/lib/tftpboot.template /var/lib/tftpboot

## html ubuntu files ##
#    - name: Adding the ubuntu directory
#      command: scp -r root@192.168.150.199:/etc/ansible/templates/html.ubuntu.template /var/www/html/

#    - name: Renaming the directory
#      command: mv /var/www/html/html.ubuntu.template /var/www/html/ubuntu

## html preseed files ##
#    - name: Adding the preseed directory
#      command: scp -r root@192.168.150.199:/etc/ansible/templates/html.preseed.template /var/www/html/
#
#    - name: Renaming the directory
#      command: mv /var/www/html/html.preseed.template /var/www/html/preseed

...
